folio-org/mod-record-specifications

README.md, compose.yml, docs/development.md
- Update README
- Create additional development documentation
- Update compose.yml
=> docs: update documentation

mod-record-specifications-server/src/main/java/org/folio/rspec/domain/repository/FieldRepository.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/sync/fetcher/MarcSpecificationBlockSplitter.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/sync/fetcher/MarcSpecificationFieldBuilder.java, mod-record-specifications-server/src/main/resources/db/changelog/changes/v1.0/data/specification-metadata-authority.json, mod-record-specifications-server/src/main/resources/db/changelog/changes/v1.0/data/specification-metadata-bibliographic.json, mod-record-specifications-server/src/main/resources/db/changelog/changes/v1.0/populate-default-data.xml, mod-record-specifications-server/src/test/java/org/folio/rspec/service/sync/fetcher/FullMarcSpecificationParserTest.java, mod-record-specifications-server/src/test/java/org/folio/rspec/service/sync/fetcher/MarcSpecificationFieldBuilderTest.java, mod-record-specifications-server/src/test/resources/__files/marc/authority.html
- fix parser for sync endpoint
- have sorted fields in response
- add LDR (000) field to spec metadata
https://folio-org.atlassian.net/browse/MRSPECS-12
=> fix(specification-storage): fix parser for sync endpoint

NEWS.md, mod-record-specifications-server/src/main/java/org/folio/rspec/controller/handler/ScopeModificationNotAllowedExceptionHandler.java, mod-record-specifications-server/src/main/java/org/folio/rspec/domain/dto/ErrorCode.java, mod-record-specifications-server/src/main/java/org/folio/rspec/domain/entity/Field.java, mod-record-specifications-server/src/main/java/org/folio/rspec/exception/ScopeModificationNotAllowedException.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/SpecificationFieldService.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/mapper/FieldMapper.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/validation/scope/ScopeValidator.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/validation/scope/field/FieldLocalScopeValidator.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/validation/scope/field/FieldStandardScopeValidator.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/validation/scope/field/FieldSystemScopeValidator.java, mod-record-specifications-server/src/test/java/org/folio/api/SpecificationStorageFieldsApiIT.java, mod-record-specifications-server/src/test/java/org/folio/api/SpecificationStorageSyncApiIT.java, mod-record-specifications-server/src/test/java/org/folio/rspec/service/SpecificationFieldServiceTest.java, mod-record-specifications-server/src/test/java/org/folio/rspec/service/validation/scope/field/FieldScopeValidatorTest.java, mod-record-specifications-server/src/test/java/org/folio/support/IntegrationTestBase.java, mod-record-specifications-server/src/test/java/org/folio/support/builders/FieldBuilder.java, translations/mod-record-specifications/en.json
- add limitations for modifiing and deleting system/standard field definitions
- Allow to update tag for local scope fields
https://folio-org.atlassian.net/browse/MRSPECS-11
=> feat(specification-storage): add limitations for modifiing and deleting system/standard field definitions

mod-record-specifications-server/src/main/java/org/folio/rspec/controller/handler/HttpMessageNotReadableExceptionHandler.java, mod-record-specifications-server/src/main/java/org/folio/rspec/domain/dto/ErrorCode.java, mod-record-specifications-server/src/test/java/org/folio/api/SpecificationStorageIndicatorsApiIT.java, mod-record-specifications-server/src/test/java/org/folio/rspec/controller/SpecificationStorageFieldsControllerTest.java, mod-record-specifications-server/src/test/java/org/folio/rspec/controller/SpecificationStorageIndicatorsControllerTest.java, translations/mod-record-specifications/en.json
Fix error messages
[MRSPECS-7](https://folio-org.atlassian.net/browse/MRSPECS-7)
=> fix(field-indicators): Fix error messages

mod-record-specifications-server/src/main/java/org/folio/rspec/service/mapper/FieldIndicatorMapper.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/mapper/FieldMapper.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/mapper/SpecificationMapper.java, mod-record-specifications-server/src/test/java/org/folio/api/SpecificationStorageApiIT.java
Do not include empty collections in response
Using post mapping in Mapstruct mappers
https://folio-org.atlassian.net/browse/MRSPECS-11
=> fix(specification-storage): fix response serializing

api/schemas/fieldIndicatorChangeDto.yaml, api/schemas/indicatorCodeChangeDto.yaml, api/schemas/specificationFieldChangeDto.yaml, api/schemas/subfieldChangeDto.yaml, mod-record-specifications-server/src/main/java/org/folio/rspec/config/ValidationConfig.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/validation/NotNullValidator.java, mod-record-specifications-server/src/test/java/org/folio/api/SpecificationStorageFieldsApiIT.java, mod-record-specifications-server/src/test/java/org/folio/rspec/controller/SpecificationStorageControllerTest.java, mod-record-specifications-server/src/test/java/org/folio/rspec/controller/SpecificationStorageFieldsControllerTest.java, mod-record-specifications-server/src/test/java/org/folio/rspec/controller/SpecificationStorageIndicatorsControllerTest.java, translations/mod-record-specifications/en.json
- fix error messages for blank required fields
- fix error message for deleting standard/system fields
Adjust messages, create custom NotNull Validator
https://folio-org.atlassian.net/browse/MRSPECS-11
=> fix(specification-storage): fix error messages for blank required fields

NEWS.md, api/mod-record-specifications.yaml, api/parameters/subfieldId-param.yaml, api/paths/specification-storage/indicator-codes-by-id-path.yaml, api/paths/specification-storage/subfields-by-id-path.yaml, compose.yml, descriptors/ModuleDescriptor-template.json, mod-record-specifications-dto/pom.xml, mod-record-specifications-server/src/main/java/org/folio/rspec/controller/SpecificationStorageSubfieldsController.java, mod-record-specifications-server/src/main/java/org/folio/rspec/exception/ResourceNotFoundException.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/SubfieldService.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/mapper/SubfieldMapper.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/validation/scope/ScopeValidator.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/validation/scope/field/FieldLocalScopeValidator.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/validation/scope/field/FieldStandardScopeValidator.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/validation/scope/field/FieldSystemScopeValidator.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/validation/scope/subfield/SubfieldLocalScopeValidator.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/validation/scope/subfield/SubfieldStandardScopeValidator.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/validation/scope/subfield/SubfieldSystemScopeValidator.java, mod-record-specifications-server/src/main/resources/application-dev.yml, mod-record-specifications-server/src/test/java/org/folio/api/SpecificationStorageSubfieldsApiIT.java, mod-record-specifications-server/src/test/java/org/folio/rspec/controller/SpecificationStorageSubfieldsControllerTest.java, mod-record-specifications-server/src/test/java/org/folio/rspec/exception/ResourceNotFoundExceptionTest.java, mod-record-specifications-server/src/test/java/org/folio/rspec/service/SubfieldServiceTest.java, mod-record-specifications-server/src/test/java/org/folio/support/ApiEndpoints.java, mod-record-specifications-server/src/test/java/org/folio/support/builders/FieldBuilder.java, mod-record-specifications-server/src/test/java/org/folio/support/builders/SubfieldBuilder.java
implement PUT/DELETE endpoints for subfields
- define endpoints
- implement endpoints logic
- update compose to support local dev testing
https://folio-org.atlassian.net/browse/MRSPECS-24
=> feat(specification-storage): implement PUT/DELETE endpoints for subfields

NEWS.md, api/examples/response/specificationDto.yaml, api/mod-record-specifications.yaml, api/paths/specification-storage/specifications-by-id-path.yaml, descriptors/ModuleDescriptor-template.json, mod-record-specifications-server/src/main/java/org/folio/rspec/controller/SpecificationStorageController.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/SpecificationService.java, mod-record-specifications-server/src/test/java/org/folio/api/SpecificationStorageApiIT.java, mod-record-specifications-server/src/test/java/org/folio/rspec/controller/SpecificationStorageControllerTest.java, mod-record-specifications-server/src/test/java/org/folio/rspec/service/SpecificationServiceTest.java, mod-record-specifications-server/src/test/java/org/folio/support/ApiEndpoints.java
Implement GET specification by id endpoint
[MRSPECS-50](https://folio-org.atlassian.net/browse/MRSPECS-50)
[MODQM-436](https://folio-org.atlassian.net/browse/MODQM-436)
=> feat(specification-storage): Implement GET specification by id endpoint

mod-record-specifications-server/src/main/java/org/folio/rspec/service/validation/resource/FieldValidator.java, mod-record-specifications-server/src/test/java/org/folio/api/SpecificationStorageFieldsApiIT.java, translations/mod-record-specifications/en.json
Adjust error messages on control field resource creation
[MRSPECS-39](https://folio-org.atlassian.net/browse/MRSPECS-39)
=> refactor(specification-fields): Adjust error messages on control field resource creation

.github/workflows/build-dependants.yml, NEWS.md
Adjust build dependants github workflow trigger
https://folio-org.atlassian.net/browse/MRSPECS-26
=> ci: adjust build dependants github action to be triggered only on dto/validator submodules changes

mod-record-specifications-validator/src/main/java/org/folio/rspec/validation/validator/marc/impl/MissingSubfieldRuleValidator.java, mod-record-specifications-validator/src/test/java/org/folio/rspec/validation/validator/marc/impl/MissingSubfieldRuleValidatorTest.java, translations/mod-record-specifications/en.json
fix error message format for MissingSubfieldRuleValidator
- add subfield code to error message builder
- update error messages for the "undefinedIndicatorCode" and "missingSubfield"
=> fix(subfields-validation) fix error message format for MissingSubfieldRuleValidator

NEWS.md, mod-record-specifications-validator/src/main/java/org/folio/rspec/validation/validator/marc/impl/MarcRecordRuleValidator.java, mod-record-specifications-validator/src/main/java/org/folio/rspec/validation/validator/marc/impl/UndefinedSubfieldRuleValidator.java, mod-record-specifications-validator/src/main/java/org/folio/rspec/validation/validator/marc/model/MarcRuleCode.java, mod-record-specifications-validator/src/test/java/org/folio/rspec/validation/MarcSpecificationGuidedValidatorTest.java, mod-record-specifications-validator/src/test/java/org/folio/rspec/validation/validator/marc/impl/UndefinedSubfieldRuleValidatorTest.java, mod-record-specifications-validator/src/test/java/org/folio/support/TestDataProvider.java, mod-record-specifications-validator/src/test/resources/testdata/subfields/marc-subfield-record.json, mod-record-specifications-validator/src/test/resources/testdata/subfields/marc-undefined-subfields-record.json, translations/mod-record-specifications/en.json
[MRSPECS-49](https://folio-org.atlassian.net/browse/MRSPECS-49) Implement "Undefined Subfield" Rule Validation 
Validation fails when subfield is not defined but exists in a record's field
=> feat(subfields-validation) implement "Undefined Subfield" Rule Validation

.github/workflows/api-doc.yml, NEWS.md
Fix link to APIs config file
_Fix dead link in api-doc.yml._
[MRSPECS-56](https://folio-org.atlassian.net/browse/MRSPECS-56)
=> fix(api-doc): Fix dead link

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-record-specifications-dto/pom.xml, mod-record-specifications-server/pom.xml, mod-record-specifications-validator/pom.xml, pom.xml
_Add module descriptor validator and fix validation issues_
_Add maven plugin and run it_
[MRSPECS-55](https://folio-org.atlassian.net/browse/MRSPECS-55)
=> refactor(module-descriptor): Add Module descriptor validator and fix permission name validation issue

.github/workflows/api-doc.yml
_Fix list of APIs file generation_
_modify api-doc.yml_
[MRSPECS-56](https://folio-org.atlassian.net/browse/MRSPECS-56)
=> MRSPECS-56: Fix list of APIs file generation

mod-record-specifications-dto/src/main/java/org/folio/rspec/domain/dto/UpdateRequestEvent.java, mod-record-specifications-server/src/main/java/org/folio/rspec/service/SpecificationFieldService.java
Serealized specification update request should contain type
=> fix(specification-storage): serealized specification update request should contain type

NEWS.md, mod-record-specifications-dto/pom.xml, mod-record-specifications-server/pom.xml, mod-record-specifications-validator/pom.xml, pom.xml
prepare for next development iteration v1.1.0
=> chore: prepare for next development iteration v1.1.0

NEWS.md, mod-record-specifications-server/src/main/java/org/folio/rspec/service/tenant/ExtendedTenantService.java, mod-record-specifications-server/src/test/java/org/folio/rspec/service/tenant/ExtendedTenantServiceTest.java
Fix tenant upgrade
Apply tenant existence check only to specification synchronization
[MRSPECS-71](https://folio-org.atlassian.net/browse/MRSPECS-71)
=> fix(tenant): Fix tenant upgrade not being run on schema existence

.github/workflows/api-doc.yml, NEWS.md
Fix documentation generation github workflow
- Fix generated filename
- Fix filepath for release builds
[MRSPECS-78](https://folio-org.atlassian.net/browse/MRSPECS-78)
=> docs(api-docs): Fix documentation generation github workflow - Fix generated filename - Fix filepath for release builds

NEWS.md, mod-record-specifications-dto/pom.xml, mod-record-specifications-server/pom.xml, mod-record-specifications-validator/pom.xml, pom.xml
Prepare for next development iteration 2.1.0
=> Prepare for next development iteration 2.1.0
